let js = 'amazing';
if (js === 'amazing') alert('Hello Der!');

console.log(40 + 8 - 23);
console.log("jonas");
//console.log("jonas");
let firstname = "nick";
console.log(firstname);
/*let firstname = "nick";
console.log(firstname);*/
let $function = 27;
let danger = 'danger';
console.log(true);
let javaScriptFun = true;
console.log(javaScriptFun);
console.log(typeof javaScriptFun);
console.log(typeof true);
console.log(typeof 23);
console.log(typeof 'string');
javaScriptFun = "yes";
console.log(typeof javaScriptFun);
let year;
console.log(year);
console.log(typeof null);
const ageJonas = 2020 - 1999;
const agesarah = 2020 - 2000;
console.log(ageJonas);
console.log(ageJonas * 2, ageJonas / 2, 2 ** 3);
const firstName = "gottipati";
const lastNmae = "sahinya";
console.log(firstName + " " + lastNmae);
let x = 10 + 5;
x += 10;
console.log(x);
x *= 5;
console.log(x);
x++;
console.log(x);
x--;
console.log(x);
console.log(ageJonas > agesarah);